### ISSUE TITLE
WMI Windows Agents plugin incorrectly reported as "not deprecated"

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/plugin-health-scoring#180] opened 2023-01-20 01:05 UTC
The [WMI Windows Agents plugin](https://plugins.jenkins.io/windows-slaves/) is deprecated, but its [plugin health score page](https://plugin-health.jenkins.io/scores/windows-slaves) lists that it is not deprecated.  That gives it a better score than it deserves.

## Expected result

Plugin health score for WMI Windows Agents plugin is much lower than 70.

## Actual result

Plugin health score for WMI Windows Agents plugin is 70.

**Comment by alecharp** [comment] 2023-01-20 09:29
This is interesting. I see that the plugin is marked as such in plugins.jenkins.io, but it is not in the update-center.

The update-center is not marking the plugin as deprecated (see https://github.com/jenkins-infra/update-center2/blob/master/resources/deprecations.properties). The plugin repository has the _topic_ `deprecated`.

I can see that the Plugin site API has correctly the label `deprecated` for this plugin (https://plugins.jenkins.io/api/plugin/windows-slaves), and the same for the update-center.

The problem is that in https://github.com/jenkins-infra/plugin-health-scoring/blob/ace129cab7c0a23ff7ecb83519a8437e2736e7ef/src/main/java/io/jenkins/pluginhealth/scoring/probes/DeprecatedPluginProbe.java#L44-L50, the code is only looking at the `deprecation` section of the update-center. This is when the update-center itself mark a plugin as deprecated (first link), but not when a plugin marks itself as deprecated (topic on plugin repository). 

This is a bug. 

Thank you @MarkEWaite for finding this!

**Closed** 2023-01-20 10:55 UTC
Labels: bug
